---
- type: replace
  path: /instance_groups/name=gogs/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((routing-nats-deployment))
    properties:
      route_registrar:
        routes:
        - name: gogs
          port: 8080
          tags:
            component: gogs
          registration_interval: 10s
          uris:
          - ((gogs-uri))

- type: replace
  path: /properties?/gogs/domain
  value: ((gogs-uri))

- type: replace
  path: /addons?/-
  value:
    name: bpm
    include:
      stemcell:
      - os: ubuntu-trusty
    jobs:
    - name: bpm
      release: bpm

- type: replace
  path: /releases/-
  value:
    name: routing
    version: 0.182.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.182.0
    sha1: 6e341a527a0dd2c920b54dea82156ae9bc0b29eb
- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "0.12.3"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.12.3"
    sha1: "313664d2e6d8485ffa0683979a401f7722f63a50"
