---
name: gogs

instance_groups:
- name: gogs
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10_240
  networks: [{name: default}]
  jobs:
  - name: postgres
    release: gogs
  - name: gogs
    release: gogs
- name: sanity-test
  azs: [z1]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanity-test
    release: gogs

properties:
  gogs:
    admin:    gogs
    password: ((gogs-password))
    tls_cert: ((gogs-tls.certificate))
    tls_key: ((gogs-tls.private_key))
    secret_key: ((gogs-secret-key))
  databases:
    roles:
      - tag: gogs
        name: gogs
        password: ((postgres-password))
    databases:
      - tag: gogs
        name: gogsdb
        citext: true

variables:
- name: postgres-password
  type: password
- name: gogs-secret-key
  type: password
- name: gogs-password
  type: password
- name: gogs-ca
  type: certificate
  options:
    is_ca: true
    common_name: gogsCA
- name: gogs-tls
  type: certificate
  options:
    ca: gogs-ca
    common_name: gogs
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.gogs.default.gogs.bosh"

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: gogs
  sha1: a43d0d772e7ffdd4839ac3243a4e7aca81597cb8
  stemcell:
    os: ubuntu-trusty
    version: "3586.16"
  url: https://s3.amazonaws.com/gogs-boshrelease/compiled-releases/gogs/gogs-5.2.4-ubuntu-trusty-3586.16-20180603-225257-524640581-20180603225259.tgz
  version: 5.2.4
